# Generated by Django 4.0.4 on 2022-04-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walk'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
            preserve_default=False,
        ),
    ]
