# Generated by Django 4.0.4 on 2022-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_walk_options_alter_walk_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='toy',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
